Dev/projects api
rit-sse/WebsiteTheSSEquel pull request #189
Opened 2024-11-10 18:26 UTC by grong0

it's done !!! check it out

2024-11-10 18:36 UTC, PokeJofeJr4th requested changes
Have you manually tested? I'm worried the GET routes wouldn't have the right amount of data returned without explicitly using the select clause.

2024-11-10 18:36 UTC, PokeJofeJr4th commented on next/prisma/schema.prisma
> +//It contains information about the user, the type of account, and the authentication `vider.
why?

2024-11-10 18:38 UTC, grong0 commented on next/prisma/schema.prisma
> +//It contains information about the user, the type of account, and the authentication `vider.
i actually have no idea

2024-11-10 18:41 UTC, grong0 commented on next/prisma/schema.prisma
> +//It contains information about the user, the type of account, and the authentication `vider.
fixed i suppose

2024-11-10 18:43 UTC, grong0 commented
i did :)

2024-11-10 21:37 UTC, grong0 commented
Added implementation for contributers on projects.

2024-11-11 06:50 UTC, 2nPlusOne commented
Noticed you're using a different indentation than the rest of the project. It should be 2 spaces indentation project-wide. Everyone should be set up with the same prettier formatting settings, but maybe that wasn't set up properly?

2024-11-11 17:19 UTC, grong0 commented
Yeah I noticed that too, lemme look into it.

2024-11-11 17:31 UTC, rtyocum commented
There is no prettier config file in the repo at all. Without this prettier uses the user's default settings. If you want the consistency then someone needs to add the config file, otherwise you can expect the styles not to match as it's not documented anywhere (at least I couldn't find it)

2024-11-11 17:38 UTC, grong0 commented
Yeah, I just added one on my end.
@2nPlusOne is there a doc somewhere that mentions the specific code format? I didn't see a coding format mentioned on the Onboarding Guide or any Contribution section. Might've just missed it though.

2024-11-11 20:18 UTC, 2nPlusOne commented
> Yeah, I just added one on my end. @2nPlusOne is there a doc somewhere that mentions the specific code format? I didn't see a coding format mentioned on the Onboarding Guide or any Contribution section. Might've just missed it though.

Not your fault! You're absolutely right, there isn't one. This is definitely something we should fix. [I created a ticket for this.](https://github.com/rit-sse/WebsiteTheSSEquel/issues/190) Feel free to edit it (either of you) with your additional thoughts.

2024-11-11 20:47 UTC, grong0 commented
Thanks!

2024-11-22 01:04 UTC, merged