Added the website rebuild ERD diagram
rit-sse/WebsiteTheSSEquel pull request #26
Opened 2023-09-16 20:49 UTC by joebaillie21

Added the diagram for the ERD to the documentation folder.

2023-09-16 20:52 UTC, lunarcon approved these changes
diagram looks good to me. i was wondering how we will handle and store access privileges, but I suppose that's an issue for later.

2023-09-23 15:42 UTC, 2nPlusOne requested changes

2023-09-23 15:42 UTC, 2nPlusOne commented on documentation/Website Rebuild ERD.drawio.png
This is a great start!

There are just a few things I noticed that we might want to change.
- A mentor no longer needs a course_id field since we have the courses_taken table. This leaves the mentor table with only a single column for now. We may find ourselves rethinking how to represent a mentor later on.
- We should pick a standard for table naming. I'm partial singular snake_case, but the specific standard is less important than consistency.
- Let's say the database has been running for a few semesters and the mentors have changed. If we want to retain information about past mentoring _inside the database itself_, we should probably add some way to know if a row in the schedule is current or not, e.g. an expiration date. It could be that we decide "No, let's just wipe the table after each semester or dump the data somewhere then wipe it."
- For the course(s) table, I think department and code should be merged into a single field of type varchar(10) and expect course codes to be of the form 'XXXX 123' or 'XXXX123'.

2023-09-23 15:45 UTC, 2nPlusOne commented
> diagram looks good to me. i was wondering how we will handle and store access privileges, but I suppose that's an issue for later.

The officer table, is_active bool, is_primary bool, and mentor table should be enough information to get us started with privileges.

2023-10-03 01:19 UTC, 2nPlusOne requested changes

2023-10-03 01:19 UTC, 2nPlusOne commented on documentation/Website Rebuild ERD.drawio.png
A couple of things to note in this iteration: Mentor, Courses, Skills, and Schedule still need to be made lowercase. Plural table names should also be made singular to match our agreed naming convention; namely `mentor_skill`, `course`, and `skill`.

2023-10-03 01:19 UTC, 2nPlusOne commented on documentation/Website Rebuild ERD.drawio.png
This is very minor, but you could make the `officer` table block wider so the is_active row doesn't wrap to the next line. Same with the `officer_position` and `course` tables.

2023-10-03 01:19 UTC, 2nPlusOne commented on documentation/Website Rebuild ERD.drawio.png
Based on a conversation we had at the recent tech meeting, a `user` should have columns for `github_profile_url` and `linkedin_profile_url`. Let's skip the personal website URL, because it would be hard to validate these URLs with regex to prevent people from injecting malicious URLs. In its stead, we could provide a `linktree_url`.

I chatted with Professor Rabb and got some feedback on the data model. Some points we discussed are below (in rough order of importance):

- Similar to an officer, mentors should have a `start_date`, `end_date`, and `is_active` boolean, allowing us to track mentorship data over time.
- The `user` table should have a `deactivation_date` column, allowing us to (in the future), more readily support account deactivation (active if NULL, de-active if not NULL, in addition to the actual date it was deactivated). 
- We should also add a `creation_date` column to the `user` table, giving us more information about the age of an account for analytics purposes.
- `department` should be its own table, rather than just a varchar in `course`. If department codes change over time, as CSec did recently, updating our data will be as simple as changing a single row.

2023-10-07 17:32 UTC, 2nPlusOne approved these changes

2023-10-07 17:32 UTC, merged